### ISSUE TITLE
get_error() return issue

### ISSUE THREAD

**Issue by ronmichel** [awegg/landroidcc#4]
```
    def get_error(self):
        """
        Returns the error as string. If there is no error, "No Error" is returned
        :return: The error as text
        :rtype: str
        """
        return self._state
```

should be `return self._error`

Off-topic: Did you, by any chance, already create a HASS integration/component? Could you share the code? Thanks!

**Comment by awegg** [comment]
Thanks a lot for raising this issue! I fixed it with version 0.1.2 which is already uploaded. 

I have indeed a HASS integration. Nothing cleaned up but it works for my mower since half a year. I will upload it later today with a minimal documentation and update this issue with a note.

**Comment by awegg** [comment]
I've uploaded the HASS integration to https://github.com/awegg/hass-worxlandroidcloud .

**Comment by ronmichel** [comment]
Perfect, thank you so much!
